// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/test/api/udf_function/test_templated_scalar_udf.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/test/api/udf_function/test_argumented_scalar_udf.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/test/api/udf_function/test_templated_vec_udf.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/test/api/udf_function/test_argumented_vec_udf.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/test/api/udf_function/test_aggregate_udf.cpp>
