// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/common/adbc/adbc.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/common/adbc/driver_manager.cpp>
