// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/duck_transaction_manager.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/duck_transaction.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/meta_transaction.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/undo_buffer_allocator.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/undo_buffer.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/transaction_context.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/transaction.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/transaction_manager.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/commit_state.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/rollback_state.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/cleanup_state.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/transaction/wal_write_state.cpp>
