// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/union/union_extract.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/union/union_value.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/union/union_tag.cpp>
