// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/operator/add.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/operator/arithmetic.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/operator/multiply.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/operator/subtract.cpp>
