// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/pragma/pragma_functions.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/pragma/pragma_queries.cpp>
