// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/random/random.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/random/setseed.cpp>
