// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/current.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/age.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/date_diff.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/date_sub.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/to_interval.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/time_bucket.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/date_trunc.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/epoch.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/date_part.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/date/make_date.cpp>
