// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/approx_top_k.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/quantile.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/reservoir_quantile.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/mad.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/approximate_quantile.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/holistic/mode.cpp>
