// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/struct/remap_struct.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/struct/struct_extract.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/struct/struct_pack.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/function/scalar/struct/struct_concat.cpp>
