// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/execution/operator/projection/physical_projection.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/execution/operator/projection/physical_tableinout_function.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/execution/operator/projection/physical_pivot.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/execution/operator/projection/physical_unnest.cpp>
