// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/storage/metadata/metadata_manager.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/storage/metadata/metadata_reader.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/storage/metadata/metadata_writer.cpp>
