// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/nested/binned_histogram.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/nested/list.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/aggregate/nested/histogram.cpp>
