// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/main/capi/cast/utils-c.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/main/capi/cast/from_decimal-c.cpp>
