// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_functions.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_generator.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_schemas.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_table_functions.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_types.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/src/catalog/default/default_views.cpp>
