// Unity Build generated by CMake
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/blob/base64.cpp>
#include </Users/dansiegel/Documents/projects/snowducks/duckdb/extension/core_functions/scalar/blob/encode.cpp>
